### VERSION
GET {{api}}/v1/version


### SET
POST {{api}}/v1/set
Content-Type: application/json

{
  "vals": {
    "values": [
      {
        "key": "key",
        "value": "val"
      }
    ]
  }
}

### GET
GET {{api}}/v1/get/key