// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"github.com/godverv/hello_world/internal/transport"
	"github.com/godverv/hello_world/internal/transport/grpc/api"
)

type Custom struct {
	ServerManager *transport.ServersManager
}

func (c *Custom) Init(a *App) error {
	grpcImpl := api.New(a.Sqlite, a.Cfg)

	a.Server.AddImplementation(grpcImpl)

	return nil
}
