// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"github.com/godverv/hello_world/internal/transport"
)

type Custom struct {
	ServerManager *transport.ServersManager
}

func (c *Custom) Init(a *App) error {
	c.ServerManager = transport.NewManager()
	return nil
}
