// Code generated by RedSock CLI. DO NOT EDIT.

package app

import (
	errors "github.com/Red-Sock/trace-errors"
	"github.com/godverv/hello_world/internal/clients/redis"
	"github.com/godverv/hello_world/internal/clients/sqldb"
)

func (a *App) InitDataSources() (err error) {
	a.Sqlite, err = sqldb.New(a.Cfg.DataSources.Sqlite)
	if err != nil {
		return errors.Wrap(err, "error during sql connection initialization")
	}

	a.Redis, err = redis.New(a.Cfg.DataSources.Redis)
	if err != nil {
		return errors.Wrap(err, "error during redis connection initialization")
	}

	return nil
}
