app_info:
    name: github.com/godverv/hello_world
    version: v0.0.8
    startup_duration: 10s
data_sources:
    - resource_name: sqlite
      path: ./data/sqlite/hello_world.db
      migrations_folder: ./migrations
    - resource_name: postgres
      migrations_folder: ./migrations
      host: localhost
      port: 5432
      user: hello_world
      pwd: ""
      name: hello_world
      ssl_mode: ""
servers:
    80:
        /{GRPC}:
            module: pkg/hello_world
            gateway: /v1
environment:
    - name: int_slice
      type: int
      value: '[18501-18519]'
