app_info:
    name: github.com/godverv/hello_world
    version: v0.0.10
    startup_duration: 10s
data_sources:
    - resource_name: sqlite
      path: ./data/sqlite/hello_world.db
      migrations_folder: ./migrations
servers:
    80:
        /{GRPC}:
            module: pkg/hello_world
            gateway: /v1
