app_info:
  name: github.com/godverv/hello_world
  version: v0.0.5
  startup_duration: 10s
data_sources:
  - resource_name: sqlite
    path: ./data/sqlite/hello_world.db
server:
  - name: grpc
    port: 80
environment: []
